version: '3'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  image-module:
    build: ./
    depends_on:
      - 'mongo'
    # environment:
    #   WAIT_HOSTS: mongo:27017
    ports: 
      - '3003:3003'



